### ISSUE TITLE
Failed to download converted file - Open Office XML

### ISSUE THREAD

**Issue by Innovazionedigitale** [ONLYOFFICE/onlyoffice-owncloud#102]
Hello, 
I've a problem when i try to open files like .doc, .xls, .ppt etc. because when I click on "Open in OnlyOffice" option, after the pop-up that ask me if I want to download the Open Office XML format, the system returns an error message "Failed to download converted file".
With .docx, .xlsx, .pptx or .txt files all works correctly.
I run a 11.0.1 (stable) version of Nextcloud and 1.1.3 version of OnlyOffice API.

Some ideas?

Thanks

**Comment by alexanderonlyoffice** [comment]
Hello @Innovazionedigitale ,

The reason can be that the additional URLs are not set up correctly. Please try to download the .docx file in 10 seconds after editing and check if the content has been saved in document.

**Comment by Innovazionedigitale** [comment]
@alexanderonlyoffice If I edit a .docx document and I try to download it after a few seconds, it doesn't save the changes. But if I open it on Nextcloud platform, there are changes kept ..

What do you suggest? What I have to modify for overcoming this problem?

**Comment by alexanderonlyoffice** [comment]
@Innovazionedigitale, when you are opening the document on NextCloud, it is being taken from the cache of the document server, that's why the changes are kept. 

Please note that you are using ONLYOFFICE connector version 1.1.3, the latest one is 1.1.4. It was released few days ago. 

Set up the local URLs for NextCloud and document server to solve the issue. You can find a scheme of the local network under this [link](https://api.onlyoffice.com/editors/owncloud#settings).

**Comment by Innovazionedigitale** [comment]
@alexanderonlyoffice 
I've set in the field "Document Editing Service address" my public address of the OnlyOffice Document Server.
in the field "Document Editing Service address for internal requests from the server" my public address of the OnlyOffice Document Server.
In the field "Server address for internal requests from the Document Editing Service" my public address of the Nextcloud Server.

Where am I wrong? Can you help me?

**Comment by alexanderonlyoffice** [comment]
@Innovazionedigitale 
Leave the public address of ONLYOFFICE Document Server in the first field "Document Editing Service address". Enter the internal address of ONLYOFFICE Document Server in the field "Document Editing Service address for internal requests from the server" and internal address of NextCloud in the field "Server address for internal requests from the Document Editing Service".

Please check also log files if there are any errors.

**Comment by Innovazionedigitale** [comment]
Hi @alexanderonlyoffice ,
I've tried to enter the internal addresses of my two servers, but when I save the changes the system returns me the message "Error when trying to connect (Bad request or timeout error)".
I've checked the logging section and it shows that something is wrong with "documentservice.php" file of my OnlyOffice Document Server (10.0.1.127)

![nextcloud](https://user-images.githubusercontent.com/31687320/30263075-cbbb3a22-96d3-11e7-9766-b23e60c93ebb.png)

Have you any idea of what can I do to resolve that? It's important for me to be able to work with old Microsoft Office documents.

**Comment by alexanderonlyoffice** [comment]
Please download the new version of application connector under this [link](https://github.com/ONLYOFFICE/onlyoffice-owncloud/archive/develop.zip) and follow these steps: unpack it to **_/nextcloud/apps/onlyoffice/_** => open the NextCloud config file **_/nextcloud/config/config.php_** => and add a section to it:

'onlyoffice' =>
  array (
    'verify_peer_off' => TRUE,
  )

It should resolve the problem.

**Comment by Innovazionedigitale** [comment]
@alexanderonlyoffice 
Ok, this version of application connector resolved both the problems with old Office files and changes apported to a file downloaded few seconds after editing.
Thank you so much for your help.

The last thing that started after updating the application connector is that on my admin account, Nextcloud shows the message "There have been errors with the code integrity check".

It's because is a developer version of the app?

**Comment by alexanderonlyoffice** [comment]
@Innovazionedigitale 
The problem is that this version was a test version. Please download the new one (**_onlyoffice-nextcloud.tar.gz_**) under this [link](https://github.com/ONLYOFFICE/onlyoffice-owncloud/releases).

**Comment by Innovazionedigitale** [comment]
@alexanderonlyoffice 
I've unpacked the latest version (downloaded from the link above) on my server, but the error persist and the "invalid files" log has a lot of strings more than the previous one.
I've attached it if can help to solve this problem.

[Log.txt](https://github.com/ONLYOFFICE/onlyoffice-owncloud/files/1292705/Log.txt)

**Comment by alexanderonlyoffice** [comment]
@Innovazionedigitale,
Please delete the folder **_apps/onlyoffice_** and unpack the application again. There are some files in the folder which become cause of the problem.

**Comment by Innovazionedigitale** [comment]
@alexanderonlyoffice 
I've done it but the message continue to appear ..
I've noticied that this message appears also when the application connector isn't on the server.
I've tried to login on my server to verify that really the app was removed (and so was) but the message was still there.
Before the unpacking of the development version on the server, I've never saw this message, what could have it modified that cause that problem? 
I have to tell you that the server login web page asked me to do an update when I unpacked the development version.

**Comment by LinneyS** [comment]
Restore original files of nextcloud (from your _Log.txt_):
- core
	- INVALID_HASH
		- .htaccess
		- core/css/styles.css
		- core/js/apps.js
		- core/js/login.js
		- core/templates/login.php
- files_sharing
	- INVALID_HASH
		- templates/authenticate.php

This problem is not in the onlyoffice app

**Comment by Innovazionedigitale** [comment]
Hello @LinneyS @alexanderonlyoffice 
I've restore original files of nextcloud:

.htaccess
core/css/styles.css
core/js/apps.js
core/js/login.js
core/templates/login.php
templates/authenticate.php

But i receive the same message every time i login with admin account.

**Comment by LinneyS** [comment]
What are the errors now in Log.txt?

**Comment by Innovazionedigitale** [comment]
@LinneyS 
I've cleaned my browser chronology, cache and cookies and now it says "All controls passed."
Sorry, my fault.

**Comment by Innovazionedigitale** [comment]
Hello, 

I need your help another time. 
I've installed Owncloud 10.0.3 on an Ubuntu 16.04.3 LTS machine and integrated it with Onlyoffice 1.1.5 app.

The admin interface says "There were problems with the code integrity check".
In attachment my log file because this time i can't find the files that are causing this problem.

Thank you so much.

**Comment by alexanderonlyoffice** [comment]
Hello @Innovazionedigitale,

You need to use latest signed version of the app. Please follow this [link](https://github.com/ONLYOFFICE/onlyoffice-owncloud#installing-owncloudnextcloud-onlyoffice-integration-app) (sections 2.a or 2.b).

**Comment by Innovazionedigitale** [comment]
Hello @alexanderonlyoffice,

This tutorial has resolved the problem.

Thank you so much again.
