### ISSUE TITLE
Error while downloading the document file to be converted

### ISSUE THREAD

**Issue by johaahn** [ONLYOFFICE/onlyoffice-owncloud#181]
After an upgrade to OnlyOffice 5.1.3 (deb), I'm now facing following error : “error while downloading the document file to be converted” on Admin page.

![image](https://user-images.githubusercontent.com/271832/39398639-f15dd16c-4b10-11e8-9e55-7b0aa3c737a9.png)

/var/log/onlyoffice/documentserver/converter/out.log
says : 

> [2018-04-28 16:08:42.109] [ERROR] nodeJS - error downloadFile:url=https://docs.example.net:444/apps/onlyoffice/empty?doc=RlVNUzBUcHJQUG9CRnRFaG94TDVHeFZ2bzVqSWVrVmREZWRWc2ZyWXdmdz0/eyJhY3Rpb24iOiJlbXB0eSJ9;attempt=3;code:DEPTH_ZERO_SELF_SIGNED_CERT;connect:undefined;(id=conv_check_1803620806_docx)
> Error: self signed certificate
>     at Error (native)
>     at TLSSocket.<anonymous> (_tls_wrap.js:1092:38)
>     at emitNone (events.js:86:13)
>     at TLSSocket.emit (events.js:185:7)
>     at TLSSocket._finishInit (_tls_wrap.js:610:8)
>     at TLSWrap.ssl.onhandshakedone (_tls_wrap.js:440:38)

**I'm using a self signed certificate and I have to.**

Any ideas ?

I've also added in nextcloud/config/config.php 

```
'onlyoffice' =>
array (
'verify_peer_off' => TRUE,
)
```

This settings above was enough to enable my self signed certificate on previous version.

I can access document server directly via HTTPS but not through nextcloud:
![image](https://user-images.githubusercontent.com/271832/39398623-b6a2e3b4-4b10-11e8-9e61-e7059b06d1c0.png)

**Comment by zsixSiuL** [comment]
same here!!!

**Comment by alexanderonlyoffice** [comment]
@johaahn, we have reproduced the issue. We will analyze the information we got and contact you.

**Comment by alexanderonlyoffice** [comment]
@johaahn, we have found the reason. When you use self-signed certificates they should be added to ca-certificate bundle of the OS of both servers (the one you use on Nextcloud should be added to the server with ONLYOFFICE Document Server and vice versa). The problem is that the certificate of Nextcloud should be also added to nodejs ca-certificate bundle, so the Document Server can verify it. But it is impossible for nodejs version 6, which is required for the Document Server at the moment. 

We are working on the possibility to install Document Server with the later versions of nodejs, where it is possible to add self-signed certificates. 

As a temporary solution you can disable verification of the certs by the Document Server. It should help. Please change [the value of the parameter](https://github.com/ONLYOFFICE/server/blob/e4efd09e3b0b84e89066814afc7cdc3365d6d643/Common/config/default.json#L69) `"rejectUnauthorized":` from `true` to `false` in /etc/onlyoffice/documentserver/**default.json**. After that restart all the services of the Document Server.

**Comment by alexanderonlyoffice** [comment]
@edarblanco, please send a screenshot of ONLYOFFICE address settings.

**Comment by edarblanco** [comment]
Hello, it is necessary to say that my certificate is self-signed, but leaving it out and after several tests, I have solved the problem
1. - Having a same domain generates a wildcard certificate, and imports it in all the instances that the services should run (say nextcloud, onlyoffice, zimbra)
2.- Then I added these options to nginx and ready, all linked, I can use onlyoffice, nexcloud and zimbra without problems and they all see all
add_header Strict-Transport-Security "max-age = 31536000; includeSubDomains" always;
add_header X-Frame-Options "ALLOW-FROM https: //onlyofficeserver.domaind.tld" always;

**Comment by alexanderonlyoffice** [comment]
@edarblanco, we are glad the issue has been resolved. We will take your solution into consideration.

**Comment by runasas2017** [comment]
Sorry, but what I needed to do if I use revers proxy nginx 192.168.1.101(access to nextcloud via  proxy internal and external users). Nextcloud internal IP 192.168.1.10. Onlyoffice is installed on separate server like 192.168.1.11. I'm using lets encript certificates which are saved on proxy. Access to Nextcloud via cloud.firm.com. I wrote like addreses of onlyoffice local address. Web page onlyoffice is Present. server works. I sure the same trouble but I don't understand what and where I need to add. Please explain.

**Comment by alexanderonlyoffice** [comment]
@runasas2017, please send us the screenshot of the error.

please check the accessibility of the Document Server for the Nextcloud and vice versa using the wget command. Example: wget https://documentserver_address (on the server where Nextcloud is installed) and wget https://nextcloud_address (on the server where Document Server is installed).  

Specify also if you have added SSL certificates to the server where Document Server is installed. If your Nextcloud is using HTTPS, Document Server also should use HTTPS protocol.

**Comment by changchichung** [comment]
same issue here 
I can connect from onlyoffce to netxcloud and vice versa
and I can connect to onlyoffice 
![](http://i.imgur.com/hdLzAKs.png)
but  still get error in nextcloud settings
![](http://i.imgur.com/KWKkJnu.png)

and I modify the default.json to set rejectUnauthorized to false and restart services by supervisorctl
```
root@bc61d7159b7c:/# cat /etc/onlyoffice/documentserver/default.json |grep reject
				"rejectUnauthorized": false
root@bc61d7159b7c:/# 
root@bc61d7159b7c:/# supervisorctl restart all
onlyoffice-documentserver:spellchecker: stopped
onlyoffice-documentserver:gc: stopped
onlyoffice-documentserver:metrics: stopped
onlyoffice-documentserver:docservice: stopped
onlyoffice-documentserver:converter: stopped
onlyoffice-documentserver:metrics: started
onlyoffice-documentserver:spellchecker: started
onlyoffice-documentserver:gc: started
onlyoffice-documentserver:docservice: started
onlyoffice-documentserver:converter: started

```
But it`s still the same " Error while downloading the document file to be converted "

any suggestions ?

**Comment by mathiasconradt** [comment]
@alexanderonlyoffice This ticket has been resolved, however the problem still exists when using http. I run OO in Docker with port mapping 8000:80, I can reach <HOST>:8000 and see the OO info page saying "Document Server is running", however, in Nextcloud I get "Error while downloading the document file to be converted". Latest Docker image from repo as of today.

**Comment by alexanderonlyoffice** [comment]
@mathiasconradt, this error means that the Document Server cannot download the file from Nextcloud for conversion and editing. Have you checked if Nextcloud is accessible for the Document Server? 

Send us also the screenshot of the address settings of ONLYOFFICE integration app in Nextcloud.

**Comment by polarwinkel** [comment]
I had the same problem and solved it by adding the Document Server to the `trusted_domains`-array in the `/var/www/html/config/config.php` of the nextcloud installation.
Since the Document Server and the nextcloud-Server are in the same, isolated vLan I don't use internal encryption. There is an nginx-proxy to encrypt everything going out from it.

**Comment by ikonspirasi** [comment]
> 
> 
> @johaahn, we have found the reason. When you use self-signed certificates they should be added to ca-certificate bundle of the OS of both servers (the one you use on Nextcloud should be added to the server with ONLYOFFICE Document Server and vice versa). The problem is that the certificate of Nextcloud should be also added to [nodejs ca-certificate bundle](https://stackoverflow.com/questions/29283040/how-to-add-custom-certificate-authority-ca-to-nodejs), so the Document Server can verify it. But it is impossible for nodejs version 6, which is required for the Document Server at the moment.
> 
> We are working on the possibility to install Document Server with the later versions of nodejs, where it is possible to add self-signed certificates.
> 
> As a temporary solution you can disable verification of the certs by the Document Server. It should help. Please change [the value of the parameter](https://github.com/ONLYOFFICE/server/blob/e4efd09e3b0b84e89066814afc7cdc3365d6d643/Common/config/default.json#L69) `"rejectUnauthorized":` from `true` to `false` in /etc/onlyoffice/documentserver/**default.json**. After that restart all the services of the Document Server.

i can confirm that this solution worked for me using NC15. 
thanks!

**Comment by SlavikCA** [comment]
> As a temporary solution you can disable verification of the certs by the Document Server. It should help. Please change [the value of the parameter](https://github.com/ONLYOFFICE/server/blob/e4efd09e3b0b84e89066814afc7cdc3365d6d643/Common/config/default.json#L69) `"rejectUnauthorized":` from `true` to `false` in /etc/onlyoffice/documentserver/**default.json**. After that restart all the services of the Document Server.

@alexanderonlyoffice 
Is it possible to follow your advice in case of Docker installation? If so - how do I edit `default.json` in Docker?

**Comment by microsard81** [comment]
Hello I have the same problem in NC15.0.4. I have onlyoffice document server installed in a standalone server. I can connect to the document server, but form NC I have always this error:

> Error when trying to connect (Error occurred in the document service: Error while downloading the document file to be converted.)

Could you help me?

**Comment by Floflobel** [comment]
Same error on nextcloud 15.0.1
I have add this parameters into my nextcloud configuration:
```
  'onlyoffice' =>
  array (
    'jwt_secret' => 'XXXXXXXXX',
    'jwt_header' => 'Authorization',
    'verify_peer_off' => TRUE,
  ),
```

**Comment by microsard81** [comment]
Unfortunately it doesn't solve the issue :-(

**Comment by alexanderonlyoffice** [comment]
@ikonspirasi, I apologize for the delayed response. This message doesn't affect document editing in Nextcloud, it just appears in logs. The issue will be fixed in the next version of ONLYOFFICE connector app.

@SlavikCA, yes you can do it inside the container. Enter the container with a command sudo docker exec -it [container_id] bash, after you enter the container the path will be the same. 

@Floflobel, @microsard81, have you tried to set rejectunauthorized to false? Check the accessibility of  Nextcloud for Document Server with wget command. The error you see means the Document Server cannot download the file for conversion from Nextcloud.

**Comment by Floflobel** [comment]
For me it is corrected, it was an error in the configuration of the token.

**Comment by microsard81** [comment]
@alexanderonlyoffice Thanks a lot! I found the problem in my resolve.conf file. Now it works fine.

**Comment by kareller** [comment]
Hello,

I have same problem between owncloud and onlyoffice and tried lots of things but problem is continue.

Do you have any suggestion to fix this error?

"Error when trying to connect (Error occurred in the document service: Error while downloading the document file to be converted.)"

Thanks for your advice.

Onlyoffice is working on docker;

![53695473-38ad9200-3dcd-11e9-81b0-b699dd219bf6](https://user-images.githubusercontent.com/25711592/53695714-0c474500-3dd0-11e9-94eb-8512d0e41fff.png)

Owncloud

![screenshot_1](https://user-images.githubusercontent.com/25711592/53695716-11a48f80-3dd0-11e9-9fc8-c65b1b6c7ccd.png)

**Comment by x4team** [comment]
1000% problem in nextcloud! Since old nextcloud server establishes a connection with the new documentserver on another server, but NEW NC server not connect to both servers onlyoffice (old and new). If I solve this problem I will write here

**Comment by x4team** [comment]
UPDATE: IT' WORK!
UNDER CONDITIONS:
1) **nextcloud version 15 and below**   (install from docker or script)
    * also if the application is updated from lower versions to new (**NOT NEW INSTALL VERSION**)
2) Add to config nextcloud /nextcloud/config/config.php
`'onlyoffice' => array (
    'verify_peer_off' => true
)`
3) Change config onlyoffice:
 /etc/onlyoffice/documentserver/default.json
`rejectUnauthorized: **false**`

RESULT: snap version nextcloud is NOT WORK!

**Comment by nextcloud101** [comment]
Same problem here with the snap version 16. Tried everything with docker and without but no chance...

**Comment by x4team** [comment]
> Same problem here with the snap version 16. Tried everything with docker and without but no chance...

I have nextcloud 16 snap version on which everything works. **BUT**  it has been updated since version 15! downgrade to snap unfortunately no.
SO:
EASY TAKE the **Docker**(via docker-compose) and set the nextcloud 15 version!:
`
version: '2'
services:
  nginx:
    image : nginx:stable
    restart: always
    depends_on:
      - app
    volumes:
      - ./nginx/nginx-vhost.conf:/etc/nginx/conf.d/defaul$
      - ./nginx/certificates:/mycerts
    ports:
      - 443:443
      - 80:80
  db:
    image: mariadb
    command: --transaction-isolation=READ-COMMITTED --bin$
    restart: always
    volumes:
      - ./data/nextcloud_db:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=my_password
      - MYSQL_PASSWORD=my_other_password
      - MYSQL_DATABASE=nextcloud3
      - MYSQL_USER=nextcloud
  app:
    image: nextcloud:17.0.0
    depends_on:
      - db
    restart: always
    volumes:
      - ./app_data:/var/www/html
`
* **maybe if you save the application data to update it to 16/17 it will work**

**Comment by timmy1420** [comment]
I'm also facing this issue. In my case I have an SSL with a let's encrypt certificate. Also using a docker container. Anyone know what's going on?

**Comment by cldtech** [comment]
I have this issue right now with a fresh install. is that solved?

**Comment by biva** [comment]
Hello, I have the same problem, and I found out that my document server (docker) doesn't have access to Nextcloud: if I launch `wget myoffice.mysite.com` from docker (`docker exec -it ID_CONTAINER /bin/bash`), I don't get anything. But in fact, I can't access any site. If I do `wget 77.95.65.121` (a google IP), I can't access it either.

Any idea?

**Comment by Alonso-10** [comment]
Bonsoir moi aussi j'ai le même problème
Moi j'ai installé Onlyoffice directement sur le serveur Nextcloud et lors de l'intégration j'ai le message suivant : " Erreur durant la tentative de connexion (Une erreur s'est produite dans le service de document: Error while downloading the document file to be converted.) (version 5.6)". Et j'aimerais avoir un réponse afin de résoudre mon problème.
Merci
![é](https://user-images.githubusercontent.com/69096614/89113855-a8fa9000-d465-11ea-859b-e6a1760e17f0.PNG)

**Comment by Alexconte31** [comment]
same problem as alonso-10

**Comment by rakibulinux** [comment]
Hello, @alexanderonlyoffice @Alonso-10 and @Alexconte31, I am getting the same problem. Any help will appreciate it. 

1. Error when trying to connect (Could not detect any host) (version 5.6)
2. Error when trying to connect (Error occurred in the document service: Error while downloading the document file to be converted.) (version 5.6)

![Screenshot from 2020-09-23 13-36-57](https://user-images.githubusercontent.com/59226530/93981532-ed3d4900-fda1-11ea-9145-7584f3cb8534.png)

**Comment by PhilippSchoenbaechler** [comment]
The same problem here, since update to version 5.6 last monday.
I use a separate virtual Linux-VM (without Docker) exclusive for the documentserver run wiht nginx with LetsEncrypt certificte.
Two different Nextcloud-Servers use this documentserver - on both I have the same problem.

The status-page says, that the documentserver is running:
![OnlyOffice_Welcomescreen](https://user-images.githubusercontent.com/71818268/94124440-4914da00-fe55-11ea-9655-bd7364e70d82.jpg)

In "/var/log/onlyoffice/documentserver/converter/out.log" I see the following error:
![Error_Message](https://user-images.githubusercontent.com/71818268/94124790-c04a6e00-fe55-11ea-8a29-36bc9682fc9a.jpg)

And this is the Error on Nextcloud-Side, when I save the OnlyOffice-Konfiguration (App-Version: 6.0.0):
![Error_Message_Nextcloud](https://user-images.githubusercontent.com/71818268/94125182-541c3a00-fe56-11ea-8bd3-4a42e6d8ef61.jpg)

Any Ideas?

Thx, Philipp

**Comment by biva** [comment]
@PhilippSchoenbaechler @rakibulinux I have the feeling that the ONLYOFFICE team is more active on their own forum: I posted and communicated a lot in https://dev.onlyoffice.org/viewtopic.php?f=53&t=24615#p34913

I have the same issue, tried a lot of ideas, but never achieved to make it work (NC on Debian/Apache + OO on Docker/Proxy). I'd like to write documentation to help others, but I can't until I have succeeded (https://github.com/biva/documentation/edit/biva/admin_manual/configuration_server/onlyoffice_configuration). I would be interested by your process to install it (@PhilippSchoenbaechler I understand that it was working before ?)

**Comment by PhilippSchoenbaechler** [comment]
@biva 
Thanks for your tip 👍 

I have found the reason in my case: 
The update from Documentserver 5.4 to 5.6 have overwrite the local.json-File (/etc/onlyoffice/documentserver)!
![Solution_Onlyoffice](https://user-images.githubusercontent.com/71818268/94130217-aa8c7700-fe5c-11ea-8421-2abcaf2f1959.jpg)

I have set the values to "true" and also replaced the value "secret" with the Secret-Key that I use in the app on Nextcloud.
After this, restart the Documentserver und nginx with this command:
supervisorctl restart all
systemctl restart nginx

And tada! Now, OnlyOffice runs correctly again.

**Comment by TheWhiteKnyt** [comment]
Forgive my noobness. But I cannot for the life of me figure out where these json files are. I'm running oods and nc in dockers within an unraid install. None of my dockers have any folders in etc/. Also I ran a file search on the whole install and couldnt find anything called local.json or default.json.

**Comment by S0urC10ud** [comment]
This error can also be displayed if a wrong DNS-Server is used... Thus, a different certificate can be sent to the service and it might not be able to validate it.

**Comment by SaschaMuehl** [comment]
Hallo @alexanderonlyoffice, 
Is there meanwhile a hands-on solution for this problem?
I installed Onlyoffice via docker (latest version), use self-signed certificates and use the access via NGINX with a virtual path behind a reverse proxy server. (nextcloud and the document-server are running an the same machine but I also want to use the document-server internally)

https://192.168.178.92:4433 and https://XXX.spdns.org/onlyoffice/ are working as far I understand:
![document-server](https://user-images.githubusercontent.com/62723171/148452183-5679c6b7-b39c-4efb-9f93-6f4c2127377d.jpg)

Now I get 4 problems: 
1. Nextcloud tells me the well known problem:
![Nextcloud](https://user-images.githubusercontent.com/62723171/148452391-a3a7c671-22f1-49f0-b844-3de4fd0daad0.JPG)
2. trying to edit the default.json in Docker is not possible because there is no /etc/onlyoffice/documentserver/default.json 
How to find and edit this file?
3. where should I copy the certificates to? I generated them to the folder /app/onlyoffice/DocumentServer/data/certs

Finally, there is a 4th question which might also be a root cause of my problem. If I click on "GO TO TEST EXAMPLE" I get two different NGINX messages (a via the 404 via my URL/virtual-path and a 500 via the local ip) - 

->http**s**://xxx.spdns.org/onlyoffice =>http**s**://xxx.spdns.org/example 

![Example-Access-Error](https://user-images.githubusercontent.com/62723171/148459253-e9d7a9cf-d790-4750-9ea4-b350f22e7c17.jpg)

Could you help me please at least for my 3 problems which were discussed here?

**Comment by SergeyKorneyev** [comment]
Hi @SaschaMuehl,

1. According to your screenshot, you have the Document Server address in the "Server address for internal requests from ONLYOFFICE Docs" field, the Nextcloud address needs to be specified there.
2. The file is inside the Document Server container. You can access it with `sudo docker exec -it [container ID] bash`. The ID can be checked with the `docker ps` command.
3. You can refer to the "Running ONLYOFFICE Docs using HTTPS" section of the following guide https://helpcenter.onlyoffice.com/installation/docs-community-install-docker.aspx
4. This looks like a proxy issue at first glance, since if the Document Server is accessible at xxx.spdns.org/onlyoffice/, then the Example's address should be xxx.spdns.org/onlyoffice/example/

Also, It would be better if you created a separate issue in case you have any further questions.

**Comment by prokokbet** [comment]
Hallo @alexanderonlyoffice,
Is there meanwhile a hands-on solution for this problem?
I installed Onlyoffice via docker (latest version), use self-signed certificates and use the access via NGINX with a virtual path behind a reverse proxy server. (nextcloud and the document-server are running an the same machine but I also want to use the document-server internally) 

[Togel Hadiah Terbesar](http://149.129.213.19/)

[Togel Hadiah Terbesar](http://147.139.138.199/)

[Deposit Pulsa Tanpa Potongan](8.215.66.84)

**Comment by cndingwei** [comment]
It seems like it fixed my problems with help from the Onlyoffice forum! But I will update here too so that others can maybe get some idea’s from this.

Onlyoffice:
default.json -> “rejectUnauthorized” to false.
local.json -> “header”: “AuthorizationJwt” from “header”: “Authorization”
supervisorctl restart all

Nexcloud:
config/config.php ->
‘onlyoffice’ => array (
‘verify_peer_off’ => true,
‘jwt_header’ => “AuthorizationJwt”
)
